# modules/shared/nix-custom-conf.nix — the single owner of
# /etc/nix/nix.custom.conf.
#
# WHY THIS EXISTS. On a Determinate-managed host, /etc/nix/nix.conf belongs to
# Determinate ("do not modify! this file will be replaced!") and nix-darwin is
# told to step back with `nix.enable = false`. Determinate's generated nix.conf
# ends with `!include nix.custom.conf`, so that file is the ONE sanctioned
# channel for daemon settings on such a host — which makes it contended. More
# than one module legitimately needs a line in it:
#
#   * darwinModules.determinate-gc — disk-pressure GC + store optimisation.
#   * nas-cache — the fleet substituter and its public key, which live in
#     `nix.settings` and are therefore inert wherever nix.enable = false.
#
# `environment.etc.<name>.text` is a plain `str`. Two modules defining it is a
# conflict, not a merge, so whichever one landed second would simply fail to
# evaluate. Hence an attrset option that several modules contribute to and ONE
# place that renders it.
#
# Imported directly by its contributors (`imports = [ ... ]`), not exported as
# a flake output: module imports are idempotent, so each contributor can name
# it without coordinating, and no consumer has to know this file exists. That
# is exactly what modules/shared/ is for — see scripts/check-module-contract.sh,
# which exempts this directory from the export rule for this reason.
{
  config,
  lib,
  ...
}: let
  cfg = config.nixCustomConf;

  # nix.conf syntax: `name = value`, list values space-separated. Booleans must
  # render as true/false, NOT as Nix's own `1`/`0` coercion.
  render = name: value:
    if builtins.isBool value
    then "${name} = ${lib.boolToString value}"
    else if builtins.isList value
    then "${name} = ${lib.concatStringsSep " " value}"
    else "${name} = ${toString value}";
in {
  options.nixCustomConf.settings = lib.mkOption {
    type = lib.types.attrsOf (lib.types.oneOf [
      lib.types.bool
      lib.types.int
      lib.types.str
      (lib.types.listOf lib.types.str)
    ]);
    default = {};
    example = {
      min-free = 1073741824;
      extra-substituters = ["http://nas-sdg.netbird.cloud:30500"];
    };
    description = ''
      Settings to write into /etc/nix/nix.custom.conf, the file Determinate's
      own nix.conf `!include`s for user overrides.

      Contributed to by any module that needs a daemon setting on a host where
      `nix.enable = false` leaves `nix.settings` inert. Rendered by
      modules/shared/nix-custom-conf.nix; attrset merge is what lets several
      modules each add their own keys without conflicting.

      Left empty the file is not written at all, so importing a contributor on
      a host that does not need it changes nothing.
    '';
  };

  # Written whenever anything contributed, rather than gated on
  # `!config.nix.enable` here: each CONTRIBUTOR decides whether its settings
  # belong in this file. determinate-gc contributes on its own `enable`, which
  # is how it behaved before this module existed, so that path is unchanged.
  config = lib.mkIf (cfg.settings != {}) {
    environment.etc."nix/nix.custom.conf".text = ''
      # Generated by nix-common (modules/shared/nix-custom-conf.nix).
      # Determinate's own /etc/nix/nix.conf `!include`s this file; do not edit
      # it by hand, and add settings through `nixCustomConf.settings` instead.
      ${lib.concatStringsSep "\n" (lib.mapAttrsToList render cfg.settings)}
    '';
  };
}
