# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  _1password-cli-linux-x64 = {
    pname = "_1password-cli-linux-x64";
    version = "2.39.0";
    src = fetchurl {
      url = "https://cache.agilebits.com/dist/1P/op2/pkg/v2.39.0/op_linux_amd64_v2.39.0.zip";
      sha256 = "sha256-b7p/N2tsbexJ9BsGQIkwpDrQZMzhA8aizls9BBOoZDQ=";
    };
  };
  _1password-gui-linux-x64 = {
    pname = "_1password-gui-linux-x64";
    version = "8.12.34";
    src = fetchurl {
      url = "https://downloads.1password.com/linux/tar/stable/x86_64/1password-8.12.34.x64.tar.gz";
      sha256 = "sha256-KXeEqmZ3C2RWB6fwTJuixK6+1PRtISAkh/UhulcrexM=";
    };
  };
  claude-code-darwin-arm64 = {
    pname = "claude-code-darwin-arm64";
    version = "2.1.252";
    src = fetchurl {
      url = "https://downloads.claude.ai/claude-code-releases/2.1.252/darwin-arm64/claude";
      sha256 = "sha256-tmHGoJT8wyZWv3wAccW0W/kAs01PChqz14/Vmuuiwsc=";
    };
  };
  claude-code-linux-x64 = {
    pname = "claude-code-linux-x64";
    version = "2.1.252";
    src = fetchurl {
      url = "https://downloads.claude.ai/claude-code-releases/2.1.252/linux-x64/claude";
      sha256 = "sha256-pxWkUQXlk/yYCNA113eB+ISAuYl5danfQYN/DFkb1LM=";
    };
  };
  codex-linux-x64 = {
    pname = "codex-linux-x64";
    version = "0.152.0";
    src = fetchurl {
      url = "https://github.com/openai/codex/releases/download/rust-v0.152.0/codex-package-x86_64-unknown-linux-musl.tar.gz";
      sha256 = "sha256-NSwk+9xa76/96cHfmRtTS2vHKgbklwh5T8aF/DVWyFU=";
    };
  };
  copilot-cli-darwin-arm64 = {
    pname = "copilot-cli-darwin-arm64";
    version = "1.0.82";
    src = fetchurl {
      url = "https://github.com/github/copilot-cli/releases/download/v1.0.82/github-copilot-1.0.82-darwin-arm64.tgz";
      sha256 = "sha256-8P7p9+7bLFEoombu1zoYfLtuoN/YHx9i4iu61/x9Pas=";
    };
  };
  copilot-cli-linux-x64 = {
    pname = "copilot-cli-linux-x64";
    version = "1.0.82";
    src = fetchurl {
      url = "https://github.com/github/copilot-cli/releases/download/v1.0.82/github-copilot-1.0.82-linux-x64.tgz";
      sha256 = "sha256-pwmqluVRNxonZfK5PdbLoj8N05DvzAd7FYxt+2ftogs=";
    };
  };
  terraform-darwin-arm64 = {
    pname = "terraform-darwin-arm64";
    version = "1.16.0";
    src = fetchurl {
      url = "https://releases.hashicorp.com/terraform/1.16.0/terraform_1.16.0_darwin_arm64.zip";
      sha256 = "sha256-XdaSxsx2tZYCn/PCsrTDoXEPktPebS2j9mvS4MLaqSo=";
    };
  };
  terraform-linux-x64 = {
    pname = "terraform-linux-x64";
    version = "1.16.0";
    src = fetchurl {
      url = "https://releases.hashicorp.com/terraform/1.16.0/terraform_1.16.0_linux_amd64.zip";
      sha256 = "sha256-QdBbknqhdPFdEijE66gyoyO3FsaLQV71oAF59GzGAtM=";
    };
  };
}
