# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  _1password-cli-linux-x64 = {
    pname = "_1password-cli-linux-x64";
    version = "2.39.0";
    src = fetchurl {
      url = "https://cache.agilebits.com/dist/1P/op2/pkg/v2.39.0/op_linux_amd64_v2.39.0.zip";
      sha256 = "sha256-b7p/N2tsbexJ9BsGQIkwpDrQZMzhA8aizls9BBOoZDQ=";
    };
  };
  _1password-gui-linux-x64 = {
    pname = "_1password-gui-linux-x64";
    version = "8.12.32";
    src = fetchurl {
      url = "https://downloads.1password.com/linux/tar/stable/x86_64/1password-8.12.32.x64.tar.gz";
      sha256 = "sha256-dg42SQNMS77+393sDP66weZ33VVIKjOQEZwaK82ifZc=";
    };
  };
  claude-code-darwin-arm64 = {
    pname = "claude-code-darwin-arm64";
    version = "2.1.245";
    src = fetchurl {
      url = "https://downloads.claude.ai/claude-code-releases/2.1.245/darwin-arm64/claude";
      sha256 = "sha256-n3wiYCUXZaGNCzUZhmnazBkS9ugSmjsB9rWNkzZf8fE=";
    };
  };
  claude-code-linux-x64 = {
    pname = "claude-code-linux-x64";
    version = "2.1.245";
    src = fetchurl {
      url = "https://downloads.claude.ai/claude-code-releases/2.1.245/linux-x64/claude";
      sha256 = "sha256-Fq0rlN6veymr7ZZtmByZkaR68EIPW+jtSj+Dvqn2eLw=";
    };
  };
  codex-linux-x64 = {
    pname = "codex-linux-x64";
    version = "0.149.1";
    src = fetchurl {
      url = "https://github.com/openai/codex/releases/download/rust-v0.149.1/codex-package-x86_64-unknown-linux-musl.tar.gz";
      sha256 = "sha256-HoUxrl9t6jxuEeU+dMxayBvxull/mylvsRLW6jD9r10=";
    };
  };
  copilot-cli-darwin-arm64 = {
    pname = "copilot-cli-darwin-arm64";
    version = "1.0.80";
    src = fetchurl {
      url = "https://github.com/github/copilot-cli/releases/download/v1.0.80/github-copilot-1.0.80-darwin-arm64.tgz";
      sha256 = "sha256-HR4GBZ0LrHONzMND3rqXzQvw0XV1TsKfg6Ckc6osa0A=";
    };
  };
  copilot-cli-linux-x64 = {
    pname = "copilot-cli-linux-x64";
    version = "1.0.80";
    src = fetchurl {
      url = "https://github.com/github/copilot-cli/releases/download/v1.0.80/github-copilot-1.0.80-linux-x64.tgz";
      sha256 = "sha256-2s6jYMgj3Vj3ENeoHDa76fZ3PfRYkIeqJctmumN8gig=";
    };
  };
  terraform-darwin-arm64 = {
    pname = "terraform-darwin-arm64";
    version = "1.15.9";
    src = fetchurl {
      url = "https://releases.hashicorp.com/terraform/1.15.9/terraform_1.15.9_darwin_arm64.zip";
      sha256 = "sha256-BbJ1hqXX2EEFaQ7MzH7bv0i8PW1Xd0XLYfFjupkK308=";
    };
  };
  terraform-linux-x64 = {
    pname = "terraform-linux-x64";
    version = "1.15.9";
    src = fetchurl {
      url = "https://releases.hashicorp.com/terraform/1.15.9/terraform_1.15.9_linux_amd64.zip";
      sha256 = "sha256-du3Qsi0vJ9PS4JfNeTIJZG9xnPYPAv869iawc2ETfaE=";
    };
  };
}
