# modules/home/pre-commit-hooks.nix — keep pre-commit's git hooks working
# across nix garbage collection.
#
# `pre-commit install` writes .git/hooks/pre-commit with three absolute
# /nix/store paths baked in: the shebang interpreter, INSTALL_PYTHON, and the
# pre-commit binary it execs. None of those is a GC root, so a store sweep can
# collect them out from under the hook — after which every commit in that repo
# dies with:
#
#   fatal: cannot exec '.git/hooks/pre-commit': No such file or directory
#
# Reinstalling fixes it only until the next sweep, because the fresh hook bakes
# equally collectable paths. This module reinstalls the hook on activation and
# then rewrites those three lines to resolve from PATH instead, which nothing
# can collect. pre-commit itself is expected in PATH via homeModules.cli-tools.
#
# Usage in a host config:
#
#   imports = [ nix-common.homeModules.pre-commit-hooks ];
#   preCommitHooks = {
#     enable = true;
#     repos = [ "${config.home.homeDirectory}/src/example" ];
#   };
{
  pkgs,
  lib,
  config,
  ...
}: let
  cfg = config.preCommitHooks;
in {
  options.preCommitHooks = {
    enable =
      lib.mkEnableOption "GC-proof pre-commit git hooks, reinstalled on activation";

    repos = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [];
      example = lib.literalExpression ''["''${config.home.homeDirectory}/src/example"]'';
      description = ''
        Absolute paths of git repositories whose pre-commit hooks should be
        installed and de-store-pathed on every activation. A path that is not
        a git repository, or has no `.pre-commit-config.yaml`, is skipped
        without failing activation — so a repo can be cloned later, or a
        host can list repos it doesn't have yet.
      '';
    };

    hookTypes = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = ["pre-commit"];
      example = ["pre-commit" "commit-msg"];
      description = ''
        Hook types to install in each repo. Only the types listed here get
        installed, so a config declaring e.g. `commit-msg` stages needs that
        type added or those hooks never run.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    home.activation.preCommitHooks = lib.hm.dag.entryAfter ["writeBoundary"] ''
      _pc=${pkgs.pre-commit}/bin/pre-commit
      _git=${pkgs.git}/bin/git
      _sed=${pkgs.gnused}/bin/sed

      for _repo in ${lib.escapeShellArgs cfg.repos}; do
        if [ ! -e "$_repo/.pre-commit-config.yaml" ]; then
          $VERBOSE_ECHO "pre-commit-hooks: no .pre-commit-config.yaml in $_repo, skipping"
          continue
        fi

        for _type in ${lib.escapeShellArgs cfg.hookTypes}; do
          # rev-parse resolves the hooks directory correctly whether .git is a
          # directory, a worktree pointer file, or core.hooksPath is set.
          if ! _hook=$("$_git" -C "$_repo" rev-parse --git-path "hooks/$_type" 2>/dev/null); then
            $VERBOSE_ECHO "pre-commit-hooks: $_repo is not a git repository, skipping"
            break
          fi
          # --git-path returns a path relative to the repo, not to us.
          case "$_hook" in
            /*) ;;
            *) _hook="$_repo/$_hook" ;;
          esac

          # Plain `install` (not -f): an existing hook pre-commit didn't write
          # is preserved as *.legacy rather than clobbered.
          $VERBOSE_ECHO "pre-commit-hooks: installing $_type hook in $_repo"
          ( cd "$_repo" && $DRY_RUN_CMD "$_pc" install --hook-type "$_type" >/dev/null )

          # Swap the three baked store paths for PATH lookups. Guarded on the
          # generator marker so a hand-written hook is never rewritten.
          if [ -f "$_hook" ] && grep -q "generated by pre-commit" "$_hook" 2>/dev/null; then
            $DRY_RUN_CMD "$_sed" -i \
              -e '1s|^#!.*|#!/usr/bin/env bash|' \
              -e 's|^INSTALL_PYTHON=.*|INSTALL_PYTHON=python3|' \
              -e 's|^exec /nix/store/[^[:space:]]*/bin/pre-commit |exec pre-commit |' \
              "$_hook"
          fi
        done
      done
    '';
  };
}
