name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  flake-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix --accept-flake-config flake check
